# fly.toml app configuration file generated for blogging-wit-bits on 2023-11-20T01:43:59-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "blogging-wit-bits"
primary_region = "sea"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
